name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  checks: write  # ← allow writing check runs
  contents: read  # ← default for source code

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew test

      - name: Generate test report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Gradle Tests
          path: "**/build/test-results/test/*.xml"
          reporter: java-junit

      - name: Upload coverage reports
        if: always()
        uses: codecov/codecov-action@v3
        with:
          files: "**/build/reports/jacoco/test/jacocoTestReport.xml"
